//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiBosch.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string id { get; set; }
        public string TenQuyen { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> CodeQuyen { get; set; }
    }
}
